### ISSUE TITLE
Is streamId needed?

### ISSUE THREAD

**Issue by ricea** [WICG/web-transport#74]
streamId is exposed on WebTransportStream but there are no APIs that consume it. As such, it doesn't appear to have a legitimate purpose. Unnecessarily exposing information to JavaScript can lead to security and privacy issues, so I propose removing it.

**Comment by vasilvv** [comment]
The basic idea behind exposing stream IDs is that applications may want to reference one stream inside another.  In order to do that, they would need a way to name streams.  QUIC already numbers streams internally, so it would make sense to just use that.

You're right that we're missing an inverse operation in the spec right now.  One can get an ID from the stream, but it's impossible to get the stream by ID.  I think that's mostly an oversight, and we could add that as well.

There's a question of whether we *should* do this, which is mostly about thinking through any potential downsides.  For QuicTransport, I don't see any.  For Http3Transport, we can't use the QUIC stream IDs by themselves easily (see vasilvv/webtransport#10), so we'd have to make our own, at a cost of roughly four bytes per stream.  So there are some trade-offs here that we'd need to figure out.

**Comment by ricea** [comment]
> The basic idea behind exposing stream IDs is that applications may want to reference one stream inside another. In order to do that, they would need a way to name streams. QUIC already numbers streams internally, so it would make sense to just use that.

Now I understand. That makes sense.

> There's a question of whether we should do this, which is mostly about thinking through any potential downsides.

It's the unknown downsides I'm worried about. Are we exposing ourselves to potential fingerprinting attacks? Is some software going to depend on the streamId being "secret"?

**Comment by vasilvv** [comment]
For QuicTransport, I don't think that would be an issue, as (1) underlying connection is accessible only through the object that established it, and (2) the IDs are deterministic and required to be in order.  So if one calls `await transport.createBidirectionalStream()` in a loop, the resulting stream IDs would be 0, 4, 8, 12, 16, etc.

For Http3Transport, that is indeed a concern we'd have to solve (for this and other reasons).

**Comment by pthatcherg** [comment]
Editor's discussion: sounds reasonable to remove it for now and readdress if it's requested by developer feedback.
